#!/bin/sh
### BEGIN INIT INFO
# Provides:	     pbackup
# Required-Start:    networking $remote_fs $syslog $local_fs $network $named $time
# Required-Stop:     networking $remote_fs $syslog #local_fs $network $named $time
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description: Start and stop pbackup daemon at boot and shutdown
# Description:       Start automounter script at boot, send signal to do exit procedures to the daemon at shutdown, and wait for it's exit
### END INIT INFO

LOGFILE="/var/log/pbackup$(date +"%d-%m-%y--%H-%M-%S").log"
exec >> $LOGFILE 2>&1

case "$1" in
	start)
		echo "[$(date +"%T")] Starting automounter script"
		sudo setsid bash /etc/init.d/usb >$LOGFILE 2>&1 < $LOGFILE &
	;;
	stop)
		echo "[$(date +"%T")] Stopping service..."
		proc_list=$(pgrep --exact pbackup)

		printf '%s\n' "$proc_list" | while IFS= read -r pid
		do
			echo "[$(date +"%T")] killing process $pid"
			sudo kill -10 $pid >/dev/null 2>&1
		done

		proc_list=$(pgrep --exact pbackup)

		printf '%s\n' "$proc_list" | while IFS= read -r pid
		do
			while kill -0 $pid >/dev/null 2>&1
			do
				echo "[$(date +"%T")] waiting for process $pid"
  				sleep 1
			done
		done
	;;
	*)
		echo "[$(date +"%T")] Usage: pbackup {start|stop}"
		exit 1
esac
exit 0
